### ISSUE TITLE
Calling reject on `api.add` doesn't remove plugin instance

### ISSUE THREAD

**Issue by roblav96** [Kava-Labs/ilp-sdk#38]
Example:
```typescript
// button outside of scope calls reject()
return new Promise(function(resolve, reject) {
	this.reject = reject
	switch.api
		.add({ settlerType: this.schema.settler, ...this.credentials } as any)
		.then(resolve, reject)
})
```
We should use the event pattern for this so the `almostReadyUplink` instance is immediately exposed.

**Comment by kincaidoneil** [comment]
The uplink can't be returned immediately, since it requires connecting to and performing a handshake with the upstream connector (it's also not really a cancel-able interaction).
